server:
  port: 6666
spring:
  application:
    name: mingyuan-ai
  cloud:
    config:
      enabled: false
# minimax key
  ai:
    minimax:
      api-key: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiJzeXoiLCJVc2VyTmFtZSI6InN5eiIsIkFjY291bnQiOiIiLCJTdWJqZWN0SUQiOiIxNzkzMjY2NTE2OTU5OTY5ODQ5IiwiUGhvbmUiOiIxNTE1NTk2NjE5MyIsIkdyb3VwSUQiOiIxNzkzMjY2NTE2OTUxNTgxMjQxIiwiUGFnZU5hbWUiOiIiLCJNYWlsIjoiIiwiQ3JlYXRlVGltZSI6IjIwMjQtMDYtMDggMTA6MzA6MjYiLCJpc3MiOiJtaW5pbWF4In0.lEFXsMbuzP7wSEM4sNXEIDAtAszKS4JTj1rM___6_nOLMEg7_xIyfnus1ysS9ycw2hE724SWMel1ysnp2mb1s1JJc45jQpzcQ6Oq_mSPXij4DO7wXyqKq0loAcEwY0U8GILO-MwAZqDT25S8I8l2vAnzgfsIUhNdwyJ3yIazqTnHGpSHKbBoU8waqY22h1tTiy9HOK7Jewvonyv0Fq5QtycQ1kLTO4sGEaX-_DAKkguqGTH-P0-_49WLBHrBbY1OqxBczMNMpcTEnYysztHhbglGbJ66vWUlifJ2pomQpj0OKEpSrgLG9Dzo9v7EIkEi_3bTt-hm5UHYX3LUqwu6jQ
# 千帆 key


# kimi key
kimi:
  client:
    api-key: sk-kN2nMBLXd3he7ruY5InPdEFBVmVnpo8RPAf5V5XD3ATXQIOc